- src/wifi_hal_nl80211.c
Reason for change: Need to close the socket and create a new socket for each simulated client test case
Test Procedure: moving from private test cases to xfinity cases or viceversa check for client association and make sure client is associated to the vap.
Risks: None
Priority: P1
> RDKB-58061 : simulated client is not associating to VAP

- platform/broadcom/platform.c
Reason for change: Enable EDPD for XER10 Platform as well.
Test Procedure: Check Eco Mode is working or not
Priority:P1
> RDKB-58005: [ECOMODE] Enable Eco Mode Support For WiFi Radios

- platform/raspberry-pi/platform_pi.c
Sends action frames via netlink.
-----------------------------------
Admittedly I am unsure if this is where this implementation belongs. Inspecting call sites in OneWiFi, it seems that `wifi_hal_send_mgmt_frame` would be the preferred forwarding call to make from `platform_pi.c` -- could anyone clarify?
i.e. in `platform_pi.c`:
```c
INT wifi_sendActionFrame(INT apIndex, mac_address_t MacAddr, UINT frequency, UCHAR *frame, UINT len)
{
return wifi_hal_send_mgmt_frame(apIndex, MacAddr, frame, len, frequency);
}
```
as opposed to an in-line nl80211 impl.
> platform: platform_pi.c: implement wifi_sendActionFrame

- platform/raspberry-pi/platform_pi.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
Refactor nl command code changes for RPI
Reason for change: Refactor the code for getting associated device stats using nl commands. Used existing rdk-wifi-hal API for msg creation, send and receive. 
Test Procedure: Ensure associated device stats data is populated for RPI4 device 
Risks: Medium
Priority: P1
Signed-off-by: Rakhil P E rakhilpe001@gmail.com
> Refactor nl command code changes for RPI

- platform/broadcom/platform.c
wrong condition check reset driver split_assoc_req configuration to 0
check hotspot VAPs have split_assoc_req 1 by default
wl -i wl0.3 split_assoc_req
wl -i wl1.3 split_assoc_req
wl -i wl2.3 split_assoc_req
wl -i wl0.5 split_assoc_req
wl -i wl1.5 split_assoc_req
wl -i wl2.5 split_assoc_req
Risks: Low
Priority: P1
> RDKB-58153: fixed association status for hotspot VAPs

- src/wifi_hal.c
- src/wifi_hal_nl80211_utils.c
- src/wifi_hal_priv.h
Reason for change: 802.11 prefix not required and expected only base and max supported standards as per broadcom implementation.
Test Procedure: Test spectrum analysis from GUI and should see expected supported standards modes.
> RDKB-58215 Expected base and max supported mode

- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
In phy_info_handler, update the phy rates based on presence of NL80211_BAND_ATTR_RATES. This change is required for configuring rates appropriately for 6G phy on BananaPi Hardware.
> Update phy rates based on NL80211_BAND_ATTR_RATES in phy_info_handler and Changes required for association with Canakit USB adapter

- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
Reason for change: enabling VNTXER5_PORT flag
Test Procedure: check CFLAG is added
and VNTXER5_PORT macro is enabled
Risks: Low
Priority: P1
Change-Id: I54e712fb1bb5c502a122641c2f4ac8d4f531e81f
> XER5-930:[Xfinity Hotspot] Connection Control and MBR

- src/wifi_hal.c
Reason for change: PHY is getting reconfigured on channel change. Test Procedure: PHY shouldn't be reconfigured on DFS to
non DFS channel change.
> RDKB-58225 : [OneWifi]Radio reconfig on Channel change

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
Reason for change: 1) Added Broadcast address for addr3 as part of wifi_hal_send_mgmt_frame. 2) Commented handling of public action frames while processing mgmt frames as it is causing duplicates. 3) Enabled noack for action frames.
Test Procedure: 1) Passpoint feature should work
2) cpu load average should be under control
Risks: Low
Priority: P0
> RDKB-58464 : high cpuload avg with failed to send action frame

- platform/qualcomm/platform_xer5.c
Reason for change: After FR mld12 mld13 interface MTU value not changing to 1600
Test Procedure: check mld12 and mld13 MTU values after FR Risks: Low
Priority: P1
> XER5-1528: After FR mld12 mld13 interface MTU value changing to 1500

- src/wifi_hal.c
Without this, the frequency parameter is unused, leading to a false impression of usefulness. The `freq` parameter can still be set to `0` to set it to the interface's frequency per the implementation of the `wifi_drv_send_mlme` function.
> Passed `freq` param through to `wifi_drv_send_mlme` function to allow for off-channel managment frame sending

- src/wifi_hal_nl80211.c
Reason for change: Raspberry Pi built in WiFi and adapters does not support ACL functionality, thus
do not invoke the call.
Test Procedure: Tested beacon working and set_ssid working with Easymesh agent and controller.
Risks: Low
Priority: P0
> RDKB-58538: Do not invoke ACL functionality in Raspberry Pi

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
- src/wifi_hal_rdk_framework.h
Impacted Platforms: All onewifi platforms
Reason for change: Implementation for XWIFI reject telemetry marker
Test Procedure: 1. Change the maximum client to 2.
2. Try to connect more than 2 clients.
3. Check the wifihealth.txt file.
Risks: Low
Priority: P1
Change-Id: I2cf2ba023c94c57951e658b13b4cde1f375b0fd5 Signed-off-by:RaviShankar.R_Rangaraj@comcast.com
> RDKB-57124: XWIFI reject telemetry marker

- platform/broadcom/platform.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_priv.h
When channel is changed hostap needs to set new beacon buffer
with CSA IEs. In case of automatic channel change by driver CSA IEs
are missing. To avoid this auto channel selection for DFS radar
event is disabled in driver and enabled in application.
- enable mgt frame control dmcli eRT setv Device.WiFi.AccessPoint.2.X_RDKCENTRAL-COM_HostapMgtFrameCtrl bool true dmcli eRT setv Device.WiFi.ApplyAccessPointSettings bool true
- enable DFS dmcli eRT setv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.DFS.Enable bool true
- set DSF channel dmcli eRT setv Device.WiFi.Radio.2.Channel uint 100 dmcli eRT setv Device.WiFi.ApplyRadioSettings bool 1
- trigger radar event wl -i wl1 radar 2
- check channel is changed
- check CSA IE are available in beacon before …
> RDKB-57507: set new channel when radar detected

- platform/broadcom/platform.c
All RDKB Platforms
Reason for change: Implement NL version of wifi_setApManagementFramePowerControl
- Set mgt frame power offset: dmcli eRT
Device.WiFi.AccessPoint.2.X_RDKCENTRAL-COM_ManagementFramePowerControl int -2
dmcli eRT setv Device.WiFi.ApplyAccessPointSettings bool 1
- check in driver wl -i wl1.1 bcnprs_txpwr_offset
Risks: Low
Priority: P1
Signed-off-by:Pavithra_Sundaravadivel@comcast.com
> RDKB-54047 NL based wifi_setApManagementFramePowerControl

- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211_utils.c
Reason for change: Enable AKM suite selector 00-0F-AC:24 and GCMP-256 for pairwise cipher.
1. Load build
2. Verify wifi-5/wifi-6/wifi-7 client connectios in below modes
WPA3-Personal-Transition with 802.11be ON
WPA3-Personal-Transition with 802.11be OFF
WPA3-Personal with 802.11be ON
WPA3-Personal with 802.11be OFF
Priority: P1
Risks: Low
> RDKB-58535: XCAM2 not able to connect(wifi7 interoperability)

- src/wifi_hal.c
Reason for change: HAL changes for setting mode.
Test Procedure: ACL set should work over Netlink.
Risks: Low
Priority:P0
> RDKB-56764 RDKB-58193: ACL over NL80211 - 2.

- src/wifi_hal_nl80211.c
- improve STA connection logs for debugging
- reopen NL socket in case of error Test Procedure:
- check wifiHal log has information about auth, assoc, eapol 
Risks: Low
Priority: P1
> RDKB-58678: add STA connection debug logs

- platform/raspberry-pi/platform_pi.c
Reason for change: Adding stub function for R-Pi
Test Procedure: NA
Risks: None
Priority:P1
> RDKB-58155 Set MgmtPower for xfinity hotspot vaps

- platform/raspberry-pi/platform_pi.c
- src/wifi_hal_nl80211.c
Add MAC ACL Support for RPI4 device
Reason for change: Added MAC ACL Support for Raspberry-Pi device by patching RPI kernel
Defined wifi_setApMacAddressControlMode function for setting the MAC address filter control
mode for the specified AP. The valid values are:
* 0: Filter disabled
* 1: Filter as whitelist
* 2: Filter as blacklist
Test Procedure: Ensure MAC ACL support is working as expected Risks: Medium
Priority: P1
Signed-off-by: Rakhil P E <rakhilpe001@gmail.com>
> Add MAC ACL Support for RPI4 device

- src/wifi_hal_hostapd.c
RDKBWIFI-24: Add vendor_ies to beacons/probes on hostapd_init_bss
Reason for change: Currently, additional vendor information elements (CCE, etc) cannot be added.
Risks: Low
Priority: P0
This code has been end-to-end tested on the Raspberry Pi with a third-party USB Wi-Fi adapter (Mediatek) **and** the built-in Raspberry Pi Broadcom chip—both work.
**Depends on HAL Interface PR [#22](https://github.com/rdkcentral/rdkb-halif-wifi/pull/22) to work**
**See the corresponding [OneWiFi PR](https://github.com/rdkcentral/OneWifi/pull/59) for information on testing**
> RDKBWIFI-24: Add vendor_ies to beacons/probes on hostapd_init_bss

- src/wifi_hal_hostapd.c
Reason for change: VAP configuration issue on XB10
Test Procedure: check XB10 6GHz VAP is up
Risks: Low
Priority: P1
> RDKB-58713: enable MBSSID feature only for XB7 and XB8

- src/wifi_hal_nl80211.c
Reason for change:  enabled hostap authentication for rdk-wifi-emulator hal. so that WPA2 auth events will be forwarded and responded.
Test Procedure: Simulated client with WPA2 security should connect to AP in onewifitest suite
Risks: Low
Priority: P1
> RDKB-58819: Sim client not connecting to AP with WPA2

- src/wifi_hal_hostapd.c
Reason for change: WPA3 mgmt key selection was misseing
in case of stored beacon/probe response
Risks: Low
Priority: P1
> RDKB-58427: Add WPA3 mgmt key for sta

- platform/raspberry-pi/platform_pi.c
- src/wifi_hal.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_nl80211_utils.c
- src/wifi_hal_priv.h
- src/wifi_hal_rdk_util.c
Reason for change: Changes in wifi-hal to support MultiVAP configuration
and to support wlan interface as AL_MAC.
Change in platform_pi to read backhaul sta configuration
Change in other files to support backhaul sta connection in EM mode.
Change to read and update almac_address and colocated mode from
EasymeshCfg.json to OneWifi.
Change to retry enabling secondary interface when it fails for first
time by bringing down the primary interface, required for Canakit adapter
> RDKB-58602: [rdk-wifi-hal] MultiVAP, WiFi backhaul as AL_MAC

- platform/broadcom/platform.c
Impacted Platforms: All RDKB platforms
Reason for change: During Ccsp to OneWifi migration, there's no validation for the invalid characters in SSID.
1. Load the device with CGA4332COM_6.7p11s1_PROD_sey.
2. And CDL the device to CGA4332COM_7.6p6s1_PROD_sey
3. And check for the log print hal_cap.wifi_prop.numRadios is out of range is flooding in /rdklogs/logs/wifiDMCLI.txt.
Risks: Medium
Priority: P1
Signed-off-by: sanjayvenkatesan1902@gmail.com
> RDKB-58696: hal_cap.wifi_prop.numRadios is out of range

- platform/broadcom/platform.c
RDKB-58696: hal_cap.wifi_prop.numRadios is out of range
Impacted Platforms: All RDKB platforms
Reason for change: During Ccsp to OneWifi migration, there's no validation for the invalid characters in SSID.
1. Load the device with CGA4332COM_6.7p11s1_PROD_sey.
2. And CDL the device to CGA4332COM_7.6p6s1_PROD_sey
3. And check for the log print hal_cap.wifi_prop.numRadios is out of range is flooding in /rdklogs/logs/wifiDMCLI.txt.
Risks: Medium
Priority: P1
Signed-off-by: sanjayvenkatesan1902@gmail.com
> RDKB-58696: hal_cap.wifi_prop.numRadios is out of range (#78)

- platform/qualcomm/platform_xer5.c
Reason for change: revert XER5-1348
Test Procedure: No issues with other builds
Risks: Medium
Priority: P1
> XER5-1607: Revert g mode support change

- platform/banana-pi/platform.c
Reason for change:  Added 6g support in BPI
Test Procedure: Able to connect 6g clients
Risks: Low
> RDKBACCL-611 : 6g interface needs to be added under the bridge in bpi platform

- src/wifi_hal.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_utils.c
- src/wifi_hal_priv.h
- src/wifi_hal_rdk_framework.h
- src/wifi_hal_rdk_util.c
Tech-XB7, Tech-XB8, CBRv2
Reason for change: To add WPA3-Personal-Compatibility mode in onewifi and rdk-wifi-hal
Test Procedure: Enable WPA3-Compatibility RFC and set security mode as
WPA3-Personal-Compatibility.
Check Client connectivity and internet
Risks: Medium
Priority:P1
Signed-off-by:Amalesh_Nandh@comcast.com
Signed-off-by:Harshavardhan_Pulluru@comcast.com
> RDKB-58443 RDKB-58446 Add WPA3-Compatibility Configuration and Telemetry

- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
Tech-XB7, Tech-XB8, CBRv2, XB10
Reason for change: Update sae_pwe for hostap-2.10 and above
Test Procedure: Enable WPA3-Compatibility RFC and set security mode as
Check Client connectivity and internet
Risks: Low
Priority:P1
Signed-off-by:Amalesh_Nandh@comcast.com
> RDKB-58446 Update sae_pwe for hostap-2.10 and above

- platform/qualcomm/platform_xer5.c
- src/wifi_hal_nl80211.c
Reason for change: fix warnings
Test Procedure: Verify XER5 build
Risks: None
Priority: P1
Change-Id: I6ac40b429f6b82cf1d8af975f3c0342cfd58a638
> XER5-240: Enable '-Werror' in XER5 rdk-wifi-hal recipe

- platform/xle/platform_xle.c
MIssing platform callback inside platform_xle.c caused build to fail
Signed-off-by:RaviShankar.R_Rangaraj@comcast.com
> RDKB-59179:Resolving XLE Build failure(6G Keep-Out)

- src/wifi_hal_dpp.c
Reason for change: Fix memory leaks related to the usage of cJSON_Parse and cJSONPrint.
Test Procedure: Expected result - No memory leaks
Risks: None
Signed-off-by: venkatakrishna.vanga@cognizant.com
> RDKBDEV-3009 : Fix memory leaks in "rdk-wifi-hal"

- src/wifi_hal.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_nl80211_utils.c
wifi_radio_operation_t structure has duplicate operating class variables op_class and operatingClass. Modify to use operatingClass and remove usage of op_class variable in rdk-wifi-hal.
Test Procedure: ssid change, radio info change tested with Easymesh agent and controller.
> RDKB-59259: Change to use operatingClass variable of wifi_radio_operation_t

- platform/broadcom/platform.c
- src/wifi_hal_nl80211.c
- enable hostap auth reply
- revert woraround to block hostap auth reply 
Risks: Low
Priority: P1
> RDKB-59304: set hostap auth configuration

- platform/broadcom/platform.c
- platform/qualcomm/platform_xer5.c
- platform/raspberry-pi/platform_pi.c
- platform/xle/platform_xle.c
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_utils.c
- src/wifi_hal_priv.h
RDKB-59179:6G Keep Out Channels list
OneWifi platforms
Reason for change: OneWifi platforms with 6G Radios must be able to exclude specific channels which are sent by MeshAgent
Test Procedure: Send the configuration via blob/multipartRoot and try to see if the excluded channels are not selected by giving a reboot/OneWifi restart.
Risks: Low
Signed-off-by:Srijeyarankesh_JS@comcast.com1
> RDKB-59179:Porting 6G keep Out Channels list to stable2(main)

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
Reason for change: Changes for getting EAPOL pcaps for external client. Test Procedure: On Ext client connection we should see eapol pcaps on cci. Risks: Low
Priority:P0
> RDKB-59089 : network connection between pi and gateway (#114)

- src/wifi_hal_nl80211.c
Added work around change for RPI.
1. Bring up the device and check for SSIDs are UP or not using "iw dev" command.
2. SSIDs should be broadcasted. Risks: None
> REFPLTB-3409: New NL80211 for ACL import changes causing AP issues in RPI

- platform/banana-pi/platform.c
- platform/intel/platform.c
- platform/raspberry-pi/platform_pi.c
- platform/wifi-emulator/platform_emulator.c
- src/wifi_hal.c
- src/wifi_hal_anqp.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
**Depends on `halinterface` [PR #33](https://github.com/rdkcentral/rdkb-halif-wifi/pull/33)**
Reason for change: To allow for off-channel action-frame sending with an optionally provided time for the channel to wait/dwell/remain on.
Test procedure: 
For off channel scanning: Call the `wifi_sendActionFrame` with a `freq != 0` and observe the call in the `cfg_80211:rdev_mgmt_tx` and `cfg_80211:rdev_return_int_cookie` ftrace (example below) or in a monitor mode capture on that channel.
```shell
OneWifi-68665   [003] ..... 123730.013302: rdev_mgmt_tx: phy1, wdev(1), band: 0, freq: 2437.000, offchan: true, wait: 0, no cck: false, dont wait for ack: true
OneWifi-68665   [003] ..... 123730.013311: rdev_return_int_cookie: phy1, returned 0, cookie: 4294967295
```
For off-channel scanning + wait: …
> RDKBWIFI-31: Added off-channel mgmt frame sending + wait parameter

- platform/broadcom/platform.c
- src/wifi_hal_nl80211.c
- enable hostap auth reply
- revert woraround to block hostap auth reply Test Procedure:
Risks: Low
Priority: P1
> RDKB-59304: set hostap auth configuration (#120)

- src/wifi_hal_nl80211_events.c
Reason for change: When sending management frames from a station interface, rdk-wifi-hal linked programs (like OneWifi) will SEGFAULT when a `tx_status` is received because only APs can have a `hapd` allocated.
Test procedure: Send a management frame from a STA interface and once the `tx_status` is returned (whether immediately or after the dwell time), a segfault will occur.
Priority: P1
Risks: Low
> RDKBWIFI-31: Fixes segfault due to no hapd present for sta interfaces

- platform/broadcom/platform.c
Reason for change : To fix onewifi build failure on Broadcom platform
> 15:19:04  | ../../../git/source/core/wifi_ctrl_queue_handlers.c:3117: error: undefined reference to 'wifi_sendActionFrameExt'
> 15:19:04  | collect2: error: ld returned 1 exit status
> 15:19:04  | make[3]: *** [Makefile:1492: OneWifi] Error 1
added new api wifi_sendActionFrameExt definition to Broadcom platform file.
> RDKBWIFI-31: Adding new sendAction frame api to Broadcom platform file

- platform/broadcom/platform.c
- platform/qualcomm/platform_xer5.c
- platform/xle/platform_xle.c
- src/wifi_hal_nl80211_events.c
Reason for change : To fix OneWifi build error due to lack of `wifi_sendActionFrameExt` implementation. Also to fix build error because of cookie `snprintf` format for different architectures
@amarnathhullur
> RDKBWIFI-31: Fixed: Compile error lack of `wifi_sendActionFrameExt` support

- platform/banana-pi/platform.c
- src/wifi_hal.c
Reason for change:  Errors are below,
translate_onewifi_dml_data:202 Dev-Init decode fail print_config:1907:Network:
print_config:1908:Controller MAC:00:00:00:00:00:00	Controller AL MAC:00:00:00:00:00:00	Agent AL MAC:00:00:00:00:00:00 print_config:1910:Manufacturer:	Manufacturere Model:	SoftwareVersion: Test Procedure: Able to run local em_agent
Risks: Low
> RDKBACCL-673 : Observing runtime errors in EM Agent

- platform/broadcom/platform.c
Reason for change: EHT capabilities missing in beacon Test Procedure:
Check EHT cap in beacon when hostap mgt frame ctrl enabled
Risks: Low
Priority: P1
> RDKB-59279: fixed EHT capabilities for XER-10

- src/wifi_hal_nl80211.c
Reverting the work around change added for ACL support.
1. Bring up the device and check for SSIDs are UP or not using "iw dev" command.
2. SSIDs should be broadcasted. 
Risks: None
> REFPLTB-3426: Porting kernel patches to support ACL for RPI

- platform/banana-pi/platform.c
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_wnm_rrm.c
Reason for change: Fixing build and runtime issue on OpenWRT platform.
Risks: Low
Test Procedure: Tested on BPI openWRT with agent, RPI collocated mode.
> RDKB-59404: OpenWRT related rdk-wifi-hal change

- platform/banana-pi/platform.c
Reason for change: Resolve the multiple re-definition issue seen on RDKB based BPI build due to initial OpenWRT based change.
Test Procedure: Compilation tested on both openWRT and RDKB builds
> RDKB-59404: OpenWRT related rdk-wifi-hal additional change

- src/wifi_hal_nl80211_utils.c
RDKB-59512: Easymesh - Mesh BackHaul changes for colocated agent
Reason for change: In colocated mode, if there is single vap at al mac address, configure it as mesh_backhaul
Test Procedure: Ensure single vap at al mac address is configured as mesh_backhaul and connection to mesh_backhaul is successful
Risks: Medium
Priority: P1
> RDKB-59512: Easymesh - Mesh BackHaul changes for colocated agent

- src/wifi_hal_nl80211.c
Reason for change: wrong attr check for max MBSSID interfaces 
cat /tmp/wifiHal | grep -i mbssid
mbssid: max interfaces 8, max profile periodicity 0
Risks: Low
Priority: P1
> RDKB-59519: fixed MBSSID attribute check

- platform/banana-pi/platform.c
Reason for change: eht_supported has to be enabled for hostapd 2.12, it has to filled
Test Procedure: Command to check core file is ls /tmp/*core*
Risks: None.
> RDKBACCL-708 : onewifi core is formed with hostap 2.12

- platform/banana-pi/platform.c
Reason for change: Adding fetching capabilities for BPI platform
Test Procedure: systemctl status onewifi
Risks: None.
> RDKBACCL-668 : Jumping Hostapd 2.11 to 2.12 for wifi 7 MLO

- platform/raspberry-pi/platform_pi.c
If running on a Raspberry Pi, the HAL now respects that an interface is an AP mesh backhaul from `InterfaceMap.json` and pulls in credentials for the BSS from `EasymeshCfg.json`
`InterfaceMap.json` on Pi with USB Wi-Fi dongle (since Pi base radio doesn't support Multi-VAP):
```
{
"PhyList": [
{
"Index": 0,
"RadioList": [
{
"Index": 1,
"RadioName": "wlan0",
"InterfaceList": [
{
"InterfaceName": "wlan0",
"Bridge": "brlan0",
"vlanId": 0,
"vapIndex": 0,
"vapName": "private_ssid_5g"
}
]
}
]
},
{
"Index": 1,
"RadioList": [
{
"Index": 0,
"RadioName": "wlan1",
"InterfaceList": [
{
"InterfaceName": "wlan1",
"Bridge": "brlan0",
"vlanId": 0,
"vapIndex": 1,
"vapName": "mesh_backhaul_2g"
}
]
}
]
}
]
}
```
On co-located EasyMesh Controller+Agent:
```
tpolomik@raspberrypi:~/rdk-easymesh-dev/rdk-wifi-hal …
```
> If a VAP is mesh backhaul, pull SSID from EashmeshCfg.json

- src/wifi_hal_nl80211.c
- Same SSID flag in RNR IE was 0
- Use MBSSID API for MBSSID flags in RNR IE 
- Check RNR IE Same SSID flag
Risks: Low
Priority: P1
> RDKB-58681: fixed same SSID RNR IE flag

- platform/raspberry-pi/platform_pi.c
Without this change, the BSS `mesh_backhaul` will have passphrase `12345678` as a default. This PR respects `Backhaul_KeyPassphrase` key from `EasymeshCfg.json` for the mesh backhaul password instead.
Very similar to my previous PR: https://github.com/rdkcentral/rdk-wifi-hal/pull/160
> platform_pi.c: pull EasyMesh mesh backhaul pw from EasymeshCfg.json

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
- src/wifi_hal_rdk_util.c
Reason for change: Selection of STA scan and candidate list should ensure sta interface radio_index should match. This is required to connect to appropriate AP in the same radio index. Test Procedure: Ensured connection with this change. Priority: P1
> RDKB-59574: Restrict sta scan and candidates to the configured radio

- src/wifi_hal_hostapd.c
Reason for change: Implement the following tr181's to support configuration of mlo params, these need to be added under Device.WiFi.AccessPoint:
mld_enable
mld_id
mld_link_id
mld_addr
mld_apply
corresponding to:
RDK_VENDOR_ATTR_MLD_ENABLE
RDK_VENDOR_ATTR_MLD_ID
RKD_VENDOR_ATTR_MLD_LINK_ID
RDK_VENDOR_ATTR_MLD_MAC
RDK_VENDOR_ATTR_MLD_CONFIG_APPLY
Test Procedure: mld_enable - true for mlo, false for slo mld_id - should be from 0 to 7 from private through mesh mld_link_id - link id of vap
mld_addr - should be bssid of vap for slo, should be bssid of first vap of the group in an mlo. mld_apply - should be 1 for the last vap in a group Priority: P1
Risks: high
> RDKB-57769: wifi tr181 to mlo configuration

- src/wifi_hal.c
XLE tries to connect old BSSID after GW is powered off
- Connect XLE to GW
- Power off GW
- Check XLE does not try connect old BSSID after scan 
tail -f /tmp/wifiCtrl Risks: Low
Priority: P1
> LTE-2578: clean scan results before new scan

- platform/raspberry-pi/platform_pi.c
- src/wifi_hal_nl80211.c
Reason for change: EHT capabilities is not present at rdk-wifi-hal
Test Procedure: Check WifiMon logs and look for 
"check_scan_complete_read_results" which ap_OperatingChannelBandwidth 
should be 320MHz for Radio2.
Priority: P1
Risks: Low
Signed-off-by: mothishree_mallaiyanjothimani@comcast.com
> RDKB-58142: Onewifi SM - Mesh (11be & 320MHz )changes for supporting Wifi-7 clients

- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_priv.h
Reason for change: Made a code changes to store bss ie and beacon ie
for all received scan ssid for 2g, 5g and 6g.
Test Procedure:1. Load the OneWifi build.
2. Test Wi-Fi STA connection.
Priority: P1
Risks: Low
Signed-off-by: aniketnarsinhbhai_Patel@comcast.com
> RDKB-59523:[OneWifi] Fix 6Ghz Wifi connectivity with WPA3-personal sec

- src/wifi_hal.c
Reason for change: To allow client connection in mesh_backhaul disable macfilter mode whitelist for easymesh
Test Procedure: Ensure with mesh_backhaul, client device can be connected.
Risks: Medium
Priority: P1
> RDKB-59512: Update macfilter mode to blacklist for easymesh

- src/Makefile.am
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
Reason for change:  Fix for build issues with latest tip
Test Procedure: Able to compile rdk-wifi-hal
Risks: Low
> RDKBACCL-737 : observing build issues in rdk-wifi-hal with latest tip code

- src/wifi_hal_nl80211.c
Reason for change: Re-Enable 4addr interface,
If it's already present.
Test Procedure: 1. Load the OneWifi build on BPI board.
2. Connected multiple BPI.
3. Tested Data traffic between end to end.
Risks: Low
Priority: P1
Signed-off-by: aniketnarsinhbhai_Patel@comcast.com
> RDKB-59503:[OneWifi]4addr additional fix support on AP and STA

- platform/qualcomm/platform_xer5.c
XER5-1638: 5Ghz is down when DFS feature is enabled
Reason for change: 5Ghz is down when DFS feature is enabled
Test Procedure: Build and test sanity
Risks: Low
Priority: P1
> XER5-1638: 5Ghz is down when DFS feature is enabled

- src/wifi_hal.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
Compilation support of TARGET_GEMINI7_2 flag
> Remove dependency with VNTXER5_PORT for DT extender device

- src/wifi_hal_nl80211_events.c
Reason for change: Fixed format specifier size_t type to resolve compile-time warning
Test Procedure: rdk-wifi-hal compilation is successful and full build as well
Risks: Low
> REFPLTB-3445: unresolved dependency for hal-wifi recipe causing build failure in RPI4 (RDKB, TDKB)

- platform/broadcom/platform.c
HUB6 - SR213
Reason for change: Hostapd migration to 2.10 version for HUB6
Test Procedure: Verify HUB6 used hostapd 2.10 and verify client connectivity.
Risks: Low
Priority: P1
> RDKB-59133 Upgrade hostap to 2.10 version for HUB6

- src/wifi_hal.c
- XLE does not have /tmp/factory_nvram.data therefore output has 0 length. 0 length is causing memory corruption. 
- Check no crash on bootup 
Risks: Low
Priority: P1
> LTE-2658: fixed memory buffer underflow

- platform/raspberry-pi/platform_pi.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
Reason for change: Added code for getting associated device stats using nl commands. Used existing rdk-wifi-hal API for msg creation, send and receive.
Test Procedure: Ensure associated device stats data is populated for RPI4 device
Risks: Medium
Priority: P1
> RDKB-57707: Add nl command code changes for RPI

- platform/raspberry-pi/platform_pi.c
Reason for change: Replace wifi_hal_stats_error_print with wifi_hal_error_print as parent optimization hal stats is not yet into stable2 branch.
Test Procedure: Ensure build issue is resolved
Risks: Medium
Priority: P1
> RDKB-57707: Fix build issue introduced by PR#200

- src/wifi_hal_nl80211.c
- Same SSID flag in RNR IE was 0
- Use MBSSID API for MBSSID flags in RNR IE Test Procedure:
Risks: Low
Priority: P1
> RDKB-58681: fixed same SSID RNR IE flag (#163)

- src/action_framework.h
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_priv.h
- src/wifi_hal_rdk_framework.h
All Onewifi Platforms
Reason for change: To monitor interop issues, added telemetry for reason ,status codes for client connectivity.
Test Procedure: connect the client ,disconnect and check the REASON_STATUS_COUNT in wifihealth.txt 
Priority: P1
Risks: Low
Signed-off-by:Harshavardhan_Pulluru@comcast.com
> RDKB-60004:Wi-Fi Telemetry to monitor interop issues with client connectivity 

- platform/broadcom/platform.c
All RDKB OneWiFi Platforms
Reason for change: Enable hostap_mgmt_frame_control by default.
Test Procedure: hostap_mgmt_frame_control should work fine and client connectivity should be successful.
Risks: Low
Priority: P1
> RDKB-59269 Enable hostap_mgmt_frame_control

- platform/broadcom/platform.c
Impacted Platforms: SKYSR213
Reason for change: Including wlioctl_defs header file.
Test Procedure: Build should be successful.
Risks: Medium
Priority: P1
> SHARMAN-3623 - [AUTO-SKY][Sprint]Latest sprint nightly build failing in jenkins

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_utils.c
- src/wifi_hal_priv.h
Reason for the change :-
- execute hostap related methods only for AP interfaces
- update vap_mode during bootup, OneWifi default values are loaded later.
- DT extender device primary interface name radio interface name doesn't match
> DTMESH-508:- Fix bootup crashes

- src/wifi_hal_nl80211.c
Currently, there is no way to get all of the results of a scan if you are scanning as a station. This allows you to get all of those results by just providing an empty (wildcard) SSID.
Call `wifi_hal_startScan` (through some means) on a station VAP with an empty SSID and see that all scan results appear. Also viewable through `/tmp/wifiHalStats`
Priority: P1
Risks: Low
Related to: 
- https://github.com/rdkcentral/OneWifi/pull/386
- https://github.com/rdkcentral/OneWifi/pull/387
> RDKBWIFI-39: Allow wildcard station scan

- src/wifi_hal.c
Reason for change:-
- changes to stop scanning if station is not present
- AP interface creation fails after successful backhaul connection in Qualcomm device if a station interface is present not associated state.
> DTMESH-515: changes to allow station deletion

- src/wifi_hal_rdk_util.c
Reason for change: Backhaul AP creation fails when bridge name is null which is not mandatory for all vaps
> DTMESH-461 [DT] Changes for Onewifi Leader mode bring-up

- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
Currently only the RSN IE is copied over to the `wifi_bss_info_t::ie` buffer. This eliminates necessary information for other applications and services, now and (I am sure) in the future. This change copies the entire BSS IE buffer to the `wifi_bss_info_t::ie` buffer and, in the cases where the `wifi_bss_info_t::ie` buffer (acting as the RSN IE) was used, a `get_ie` call is used before to get the RSN IE and pass that to the corresponding function. 
While there is an existing `wifi_interface_t::bss_elem_ie` (only used for the emulator and the BPi for some reason), that is for a specific interface, not a specific scan result. This PR is intended to bring full BSS IE access to scan results.
There were also several repeated/unnecessary instances of parsing code and …
> RDKBWIFI-38: Copies over entire BSS IE buffer to scan results and cleans up parsing

- src/wifi_hal_nl80211.c
As part of commit aa821db1344519879eda553631a83ab84f3c8e15 related to Managedwifi Phase 2 changes, NULL check on vap_cfg variable is missing which is causing a crash in BPI in nl80211_create_bridge. Fix this issue by adding NULL check of vap_cfg variable.
> RDKB-60035: Fix issue in nl80211_create_bridge

- platform/broadcom/platform.c
Reason for change: bssehtmode is 1 when EHT is disabled.
Test Procedure: Enable or disable EHT and BSS bssehtmode should be same as EHT.
Risks: None
Priority: P2
> XER10-1812 : bssehtmode does not match eht (#243)

- src/wifi_hal_nl80211.c
Reason for change: When 5G radio is operating at 36/160 configuration,
it doesn't switch bandwidth to 80MHz when radar is detected.
Test Procedure: - Set the 5G radio to channel 36 and bandwidth 160MHz with DFS enabled.
- Generate a radar detected via wl command.
- The bandwidth should switch to 80MHz.
Risks: None
Priority: P1
> XER10-1719 : 36/160 not switching to 80MHz

- src/wifi_hal.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_utils.c
- src/wifi_hal_priv.h
RDKB-60035: Amenities Network OneWifi Changes
OneWifi platforms
Reason for change: Support Managed WiFi Phase 2 configurations
Test Procedure: Send the Managed WiFi phase 2 blob and try to enable/disable.
Risks: Low
Signed-off-by:Srijeyarankesh_JS@comcast.com1
> Managedwifi Phase 2 (#213)

- platform/broadcom/platform.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
Reason for change: Emulator flags are not added to the functions at rdk-wifi-hal. Broadcom faces issue while porting to their internal platforms.
Test Procedure: Enable OneWiFiTestSuite RFC and check whether able to see the emulator related function calls at the /tmp/wifiHal logs
Priority: P1
Risks: Low
Signed-off-by: mothishree_mallaiyanjothimani@comcast.com
> RDKB-60458: Need emulator defines in rdk-wifi-hal code

- platform/xle/platform_xle.c
XLE
Reason for change: Issue with mesh backhaul and client conenctivity when HostapMgmtFrameCtrl is enabled.
Test Procedure: Verify mesh backhaul and client connectivity with HostapMgmtFrameCtrl enabled.
Risks: Low
Priority: P1
> LTE-2690 No client connectivity with HostapMgmtFrameCtrl enabled

- src/wifi_hal_nl80211_utils.c
Reason for change: To fix concat_band_to_vap_name API which got redefined as part of rdk-wifi-hal pull#235
Test Procedure: Ensure vap name configured properly with single interface
Risks: Medium
Priority: P1
> RDKB-60625: Easymesh - Fix concat_band_to_vap_name API

- src/wifi_hal_nl80211.c
RDKB-59718 Incorrect ap_SupportedStandards values for 6 GHz WiFi7 neighboring APs
Reason for change: Skip assigning 802.11g for 6 GHz band
Test Procedure: 
1. Load the custom build 
2. verify the supported standards in Neighbour stats from wifi_api and DMCLI
`wifi_api wifi_getNeighboringWiFiDiagnosticResult2 1
Device.WiFi.NeighboringWiFiDiagnostic.Result.34.SupportedStandards`
3. Enable WiFiMon logs 
4. check the value for ap_SupportedStandards in wifiMon logs
Priority: P2
Risks: Low
Signed-off-by: sneha_kannan@comcast.com
> RDKB-59718 :Incorrect ap_SupportedStandards values for 6 GHz WiFi7 neighboring APs

- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
Reason for the change:-
When leader device sends RSNXE as part of Probe response and Msg3 of EAPOL and OneWifi doesn't backup the RSNXE received during the Probe response. During msg3 of EAPOL libhostap tries to validate RSNXE against RSNXE of the scan results, And it finds mismatch leading to failure of EAPOL transaction.
> DTMESH-552 : Fix RSNXE mismatch detected during station association

- src/wifi_hal.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
Reason for change: 1) banana pi as a client needs to connect to xb gateways Test Procedure: 1) Iperf test between xb gateway and Banana pi should be successful and the artifacts are uploaded to gateway.
Risks: Low
Priority: P1
> RDKB-59829 : support to cci external client on banana-pi and iperf

- src/wifi_hal_nl80211.c
Reason for change: If RXNE is present in probe response
and H2E is set to required set it for virtual client.
Risks: Low
Priority: P1
> RDKB-60479: Check rsnxe for H2E requirement

- platform/banana-pi/kernel-patches/openwrt/0001-BPIR4_Enable_Beacon_Frame_Subscription.patch
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_priv.h
Reason for change: Implement channel change based on CSA beacon frame.
Test Procedure: Ensure channel change work in easymesh network.
Risks: Medium
Priority: P1
Signed-off-by: Rakhil P E <rakhilpe001@gmail.com>
> RDKB-60610: Implement channel change based on CSA beacon frame.

- platform/qualcomm/platform_ext.c
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
AP interface bootup fails if station interface is present.
If we delete the station interface that is affecting optimisation logic.
nl80211 send of NL80211_CMD_DISCONNECT event fails to send if EAPOL_OVER_NL is enabled.
> DTMESH-532 optimisation fails to recreate the station interface

- platform/xle/platform_xle.c
Reason for change: Invalid default phassphrase because rdkconfig_get return non-null terminated string. rdkconfig_get was replace with rdkconfig_getStr to make sure string is null terminated. Test Procedure: FR XLE and confirm if XLE can connect to gateway Risks: Low
Priority:P0
> LTE-2711: No Gateway connectivity on all backhauls, after FR (#278)

- platform/broadcom/platform.c
- src/wifi_hal_hostapd.c
Multiple times added the same link into mlo links causes for_each_mld_link(link, hapd) loop forever.
The main problem was the link was not removed properly due to conf->mld_ap was changed to false before removing the original link.
The issue was reported in connection with the configuring of BssMaxNumSta.
Enable MLO operation of all private VAPs in one MLO group.
Configure new value for BssMaxNumSta:
dmcli eRT setv Device.WiFi.AccessPoint.2.X_CISCO_COM_BssMaxNumSta int 99
dmcli eRT setv Device.WiFi.ApplyAccessPointSettings bool true
Check if new value was properly applied:
dmcli eRT getv Device.WiFi.AccessPoint.2.X_CISCO_COM_BssMaxNumSta
Priority: P1
Risks: Low
> RDKB-60772: Fixed adding/removing MLO links

- .github/workflows/cla.yml
PR #247 added copilot autofix on the action permissions.  actions:write and statuses:write are missing and causing problem with the cla.yml action.
> Fix cla.yml GitHub action.

- src/wifi_hal_nl80211.c
* XER10-1719 : 36/160 not switching to 80MHz
Reason for change: When 5G radio is operating at 36/160 configuration,
it doesn't switch bandwidth to 80MHz when radar is detected.
Test Procedure: - Set the 5G radio to channel 36 and bandwidth 160MHz with DFS
enabled.
- Generate a radar detected via wl command
- The bandwidth should be switched to 80MHz.
Risks: None
Priority: P1
> RDKB-61103 : 36/160 not switching to 80MHz (#262)

- platform/xle/platform_xle.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
XLE-WNC
Reason for change: Hostapd migration to 2.10 version for XLE and enable hostap_mgmt_frame_control by default.
Test Procedure: Verify XLE used hostapd 2.10 and verify client connectivity with hostap_mgmt_frame_ctrl enabled.
Risks: Low
Priority: P1
> RDKB-59507 Enable hostapd ver 2.10 & hostap_mgmt_frame_control for XLE

- src/wifi_hal_nl80211.c
Impacted Platforms: All RDKB platforms.
Reason for change: As nl attribute not being set from CCI,
the null pointer gets dereferenced and gets crashed.
Test Procedure: 
1. Load the above mentioned image
2.After the device got boot up , run the test trigger from vb and check 
for kernel panic and test results.
3. If KP occurs or the test trigger got failed, issue reproduced.
Risks: Medium
Priority: P0
Signed-off-by: sanjayvenkatesan1902@gmail.com
> RDKB-61227:  Facing crash reboot after triggering onewifi cases.

- src/wifi_hal_nl80211.c
All RDKB Platforms
Reason for change: Added support for WPA3-PT
Test Procedure: Trigger XH0005 test to see if its
passing
Risks: None
Priority: P0
Signed-off-by:Pavithra_Sundaravadivel@comcast.com
> RDKB-61235 CCI crashed on XB10 when executing XH0005

- platform/broadcom/platform.c
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
Reason for change: Support AMSDU TID set
Test Procedure: verify dmcli set/get AMSDU TID commands.
Risks: None
Priority: P1
> XER10-2137 : Throughput drop when boosted/prioritized on 6GHz

- platform/broadcom/platform.c
Reason for change: Add XF10 product flag support
Test Procedure: Build should work
Priority:P1
Risks:Low
> XF10-97: XF10 Bringup [rdk-wifi-hal]

- platform/banana-pi/platform.c
- src/wifi_hal.c
- src/wifi_hal_nl80211_events.c
Reason for change: Address compilation error for platform using 2.10 or lesser based hostapd to use legacy mechanism for notifying supplicant event.
Test Procedure: Compilation and build checked.
Risks: Low
Priority: P1
> RDKB-61540: Address MLO compilation issues seen on 2.10 hostap

- src/action_framework.h
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_priv.h
- src/wifi_hal_rdk_framework.h
All Onewifi Platforms
Reason for change: To monitor interop issues, added telemetry for reason ,status codes for client connectivity.
Test Procedure: connect the client ,disconnect and check the REASON_STATUS_COUNT in wifihealth.txt
Priority: P1
Risks: Low
Signed-off-by:Harshavardhan_Pulluru@comcast.com
> RDKB-60004:Wi-Fi Telemetry to monitor interop issues with client connectivity

- platform/broadcom/platform.c
- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_priv.h
Reason for change: Support AMSDU TID set
Test Procedure: verify dmcli set/get AMSDU TID commands.
Risks: None
Priority: P1
> XER10-2137 : Throughput drop when boosted/prioritized on 6GHz (#337)

- src/wifi_hal_nl80211_events.c
Reason for change: Because 5G and 6G radios share same channel number the radar event on 5G radio was also leaking to 6G. Test Procedure: Trigger radar event and check if event is only seen on 5G radio
Priority: P1
Risks: Low
> RDKB-61136: radar event is indicated in wrong radio (#305)

- src/wifi_hal_nl80211.c
Reason for change: added the check for membership selector 0xFB
Test Procedure: refer to the ticket.
Risks: None
Priority: P1
Signed-off-by: Ramakanth Taraka <ramakanth.taraka@sky.uk>
> RDKB-61364 : unsupported rate print in hal

- platform/broadcom/platform.c
Reason for change: Private VAPs were not up correctly when mlo was enabled
Test Procedure: Verify that all private VAPs are up and have the correct MLO address and BSSID after boot.
Risks: Low
Priority: P1
> BCOMB-3033: mlo re-configuration enhancements correction

- src/wifi_hal.c
Reason for change: Fix is for neighbor reports, other datamodel objects have correct mapping.
Test Procedure: Verify Device.WiFi.NeighboringWiFiDiagnostic.Result and WiFi Spectrum Analyzer values from UI
Risks: None
Priority: P1
> RDKB-59600: Fix WPA3 transition type encoding
