rdkcentral/rdk-wifi-hal

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
This pull request has two changes 
1) Change related to channel update to send correct channel information in radio subdoc.
2) Notify Assoc data in Raspberry PI platform from the new station command to make it part of associated client subdoc.
> Channel update fix and Sending Assoc frame date in associated client subdoc

- src/wifi_hal.c
Reason for change: Add missing initialization for list Test Procedure:
Risks: Low
Priority: P1
> RDKB-58009: Initialize missing list

- .gitignore
- src/wifi_hal.c
Two changes in this PR:
1) Retry channel change when EOPNOTSUPP error happens
2) Addition of .gitignore to ignore .o and related files.
> Retry when channel change fails with EOPNOTSUPP and adding .gitignore file 

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_utils.c
- src/wifi_hal_priv.h
Reason for change: With these change onewifi test suite can support with 1 to 300 clients
Test Procedure: Refer to the ticket.
Risks: Low
Priority: P1
> RDKB-58243: cci support for 300 clients

- src/wifi_hal_nl80211.c
Some driver expect the mode change to happen when interface is down, retry the mode change if it fails after setting interface to down.
Test Procedure: Tested with CanaKit Wifi USB dongle which fails mode change when interface is up and succeeds only when interface is down.
> Retry mode change after setting interface to down

- src/wifi_hal.c
- src/wifi_hal_nl80211.c
Reason for change: Implement ACL over Netlink
Test Procedure: ACl should work properly.
Risks: Low
Priority:P0
> RDKB-56764 : NL80211 Implementation for ACL

- .github/workflows/makefile.yml
Enabling build check on rdk-wifi-hal using Github actions
> Create makefile.yml for rdk-wifi-hal

- src/wifi_hal_nl80211.c
Reason for change: support of RM enabled cap in MBSSID IE 
- enable management frame control for 6GHz VAPs
- check RM enabled cap IE available in MBSSID non-tx profile if VAP has different RM cap than tx-profile 
Risks: Low
Priority: P1
> RDKB-56318: Add support of RM enabled cap in MBSSID IE

- src/wifi_hal_nl80211.c
Reason for change: Checking only for NL80211_ACL feature Test Procedure: PODs should connect properly.
Risks: Low
Priority:P0
> RDKB-58676 : POD connection is not stable

- platform/wifi-emulator/platform_emulator.c
- src/Makefile.am
Reason for change: Create platform emulator file
Risks: Low
Priority: P1
> RDKB-58427: Create platform emulator file

- platform/broadcom/platform.c
- src/wifi_hal_nl80211.c
Update beacon rate, type and flags to driver.
> RDKB-58575: BeaconRate can not be changed for 2.4/5/6G radios

- src/wifi_hal_nl80211.c
Fix for 802.11 variants based on hostapd version macro
> RDKB-58575 - XLE hostapd version macro fix

- src/wifi_hal_hostapd.c
Reverts rdkcentral/rdk-wifi-hal#21
This commit creating build errors.
```
15:44:46  | ../git/src/wifi_hal_hostapd.c:144:17: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
15:44:46  |   144 |             if (elems = wpabuf_parse_bin(vendor_oui)) {
15:44:46  |       |                 ^~~~~
15:44:46  | ../git/src/wifi_hal_hostapd.c:154:35: error: 'wifi_front_haul_bss_t' has no member named 'vendor_elements_len'
15:44:46  |   154 |     ves_len = vap_info->u.bss_info.vendor_elements_len;
15:44:46  |       |                                   ^
15:44:46  | ../git/src/wifi_hal_hostapd.c:160:43: error: 'wifi_front_haul_bss_t' has no member named 'vendor_elements'
15:44:46  |   160 |         UCHAR* ve_s = vap_info->u.bss_info.vendor_elements;
15:44:46  | …
```
> Revert "RDKBWIFI-24: Add vendor_ies to beacons/probes on hostapd_init_bss" (#21)

- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
Rebasing the rdk-wifi-hal in em-app to the latest corresponding to develop.
> Rebasing to the latest develop branch as of Feb19th

- src/wifi_hal_wnm_rrm.c
Checking the Beacon report Mode Accepts from the clients.
> Ignoring Beacon report REJECT

- src/wifi_hal_nl80211_utils.c
Reason for change: Fix compilation error
> RDKB-58602: [rdk-wifi-hal] Fix compilation error

- platform/broadcom/platform.c
**Reason for change:** MLO configuration for hostapd & passing config to driver via nl hal.
****Test Procedure:** NA
Priority:** P1
**Risks:** Low
> RDKB-57562 : Fix `SERCOMMXER10` build for NL MLO vendor commands

- src/wifi_hal.c
Reason for change: Radio op class could be different then
requested scan channel op class. Take op class based on
requested channel rather then radio channel
Test Procedure: Connect XLE/virtual sta using different bands Risks: Low
Priority:P0
> RDKB-58741 - Get op class based on requsted chan

- src/wifi_hal.c
Reason for change: Cancel scan only if all channels
are invalid
Test Procedure: RPI scan works
Risks: Low
Priority:P0
> RDKB-58741 - Validate scan channels

- platform/raspberry-pi/platform_pi.c
- src/wifi_hal.c
RDKB-59209: EM App - Channel scan changes
Reason for change: Modified the channel scan implementation based on operating class and channel. 
Added additional scan mode WIFI_RADIO_SCAN_MODE_SELECT_CHANNELS to scan only requested channels 
Test Procedure: Ensure channel scan results are received in agent side and then to controller cli upon request for channel scan. Risks: Medium 
Priority: P1
Signed-off-by: Rakhil P E <rakhilpe001@gmail.com>
> RDKB-59209: EM App - Channel scan changes

- src/wifi_hal_priv.h
- src/wifi_hal_wnm_rrm.c
Reason for change:Implement HAL apis, for Beacon Report
request and response.
Test Procedure:Beacon Report request and response
should work.
Risks: Low
Priority: P1
> RDKB-59277: Hal Changes Beacon report/response

- src/wifi_hal_nl80211.c
Reason for change: Currently station interfaces are not registered to receive management frames via NL80211 and even when they are registered and are sent from the kernel via NL80211, the HAL will filter them out because they are not an AP interface. It is required for a backhaul station to receive action frames on it's interface for DPP. Risks are low because the NL80211 call to register could always just fail because of a different kernel driver implementation which would cause an error message to be logged and no corresponding NL80211 messages to be sent, yielding the same behavior as before.
Test Procedure: Send an action frame to a station interface while subscribing to the OneWifi callback for receiving action frames. Example (unified-wifi-mesh):
```shell
mgmt_action_frame_cb:865 …
```
> RDKBWIFI-32: Adds the ability for a station interface to receive management frames

- src/wifi_hal_nl80211.c
Reason for change: Make "NL80211_ATTR_STA_VLAN" configuration
set only for BPI platform to fix this build error.
Test Procedure: 1. Load the OneWifi build on BPI board.
2. Connected multiple BPI.
3. Tested Data traffic between end to end.
Risks: Low
Priority: P1
Signed-off-by: aniketnarsinhbhai_Patel@comcast.com
> RDKB-59503:[OneWifi]Add WDS support on AP and STA

- src/wifi_hal_nl80211.c
Reason for change: frame tx fails on DFS channels
- set DFS channel
- check client can connect
Risks: Low
Priority: P1
> RDKB-59604: avoid off-channel frame tx for DFS channel

- platform/broadcom/platform.c
- platform/qualcomm/platform_xer5.c
- platform/raspberry-pi/platform_pi.c
- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211.c
- src/wifi_hal_nl80211_events.c
- src/wifi_hal_priv.h
Reason for change: MLO configuration for
hostapd & passing config to driver via nl hal.
Test Procedure: NA
Priority: P1
Risks: Med
> RDKB-57562 : MLO Configuration

- src/wifi_hal_nl80211.c
Reason for change: cancel WPS session on other radios
in case of successful connection to avoid connection of
two clients on different bands
- Check only one device can connect after pressing WPS button
Risks: Low
Priority: P1
Depend on: https://gerrit.teamccp.com/#/c/904771/
> RDKB-55943: cancel WPS session on other radios

- platform/qualcomm/platform_ext.c
Reason for change:- DT extender device doesn't use athx namimg convention.
> DTMESH-473 : Replace AP_PREFIX athx support

- platform/xle/platform_xle.c
Issue:
HE BSS Color Collision detection, handling and reporting is not enabled in the driver by default.
Root cause:
Xle platform Wlan interface color_collision configs changes were missed.
Fix:
Added the runtime configs using wl command.
> LTE-2594: [XLE][SDK-504L04P3]

- platform/broadcom/platform.c
Reverts rdkcentral/rdk-wifi-hal#198
> Revert "RDKB-59133 Upgrade hostap to 2.10 version for HUB6"

- src/wifi_hal_nl80211_utils.c
Add interfcae map changes to enable dhd offload
> LTE-2590: Enable DHD Offload for wl2 Radio

- src/wifi_hal_nl80211_utils.c
Reason for change: Fix compilation error with wifi-emulator in main branch
> RDKB-58602: [rdk-wifi-hal] Fix compilation error with wifi-emulator in main branch

- src/wifi_hal_nl80211.c
Reason for change: fixed link id and ifindex
Risks: Low
Priority: P1
> RDKB-61540: MLO support: fixed link id and ifindex

- src/wifi_hal_hostapd.c
- src/wifi_hal_nl80211_utils.c
> RDKB-61540: Fixed MLO link id lookup

- .github/release.yml
Create release.yml file, required for automation of release notes generation.
> RDKB-61715 add release.yml
